apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistry158.azurecr.io
    newTag: main-20240725053019

commonLabels:
  app: backend-java
  environment: dev
