apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistry158.azurecr.io/backend-java
    newTag: main-20240725055228

commonLabels:
  app: backend-java
  environment: dev
